#!/usr/bin/perl

# Just run the script; also try: COMPACT_BOARD=1 RANDOM_BOARD=1 script

use strict;
use warnings;

use FindBin;
use lib "$FindBin::Bin/../lib";

use Games::Checkers::Board;
use Games::Checkers::Constants;
use Games::Checkers::MoveConstants;
use Games::Checkers::BoardTree;
use Games::Checkers::BoardConstants;

my $board = Games::Checkers::Board->new($ENV{BOARD});
my $color = White;

if ($ENV{RANDOM_BOARD}) {
	my $rate = 0 + $ENV{RANDOM_BOARD};
	$rate = 1 if $rate <= 0 || $rate > 3;
	$board->clr_all;
	for my $loc (0 .. 31) {
		next if rand(4) > $rate;
		my $color = rand(2) > 1 ? White : Black;
		my $piece = rand(4) > 1 ? Pawn  : King;
		$board->set($loc, $color, $piece);
		$board->cnv($loc) if convert_type->[$color][$piece];
	}
}

my $move_counter = Games::Checkers::CountMoveList->new($board, $color);
die "Internal problem" unless $move_counter->{status} == Ok;
print "There are ", $move_counter->get_count, " possible initial moves.\n";

my $board_node = Games::Checkers::BoardTreeNode->new($board, NO_MOVE);
die "Internal problem" unless $board_node->expand($color) == Ok;

my $board_dump = $board->dump;
my $expanded_nodes = $board_node->{sons};
print $board_dump unless @$expanded_nodes;

foreach (@$expanded_nodes) {
	my $cost = $_->{board}->get_cost(Black);
	print $_->{board}->dump($board_dump, "$cost " . $_->{move}->dump);
}
